# -*- coding: utf-8 -*-
"""Untitled34.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fDFfh5Rr5qKxUuvzzTsoa9vI3gAm1H7m
"""

!pip install torch \
  torchaudio \
  transformers \
  sentence-transformers \
  openai-whisper \
  faiss-cpu \
  fastapi \
  uvicorn \
  python-multipart \
  jiwer \
  rouge-score

import whisper

class ArabicASR:
    def __init__(self):
        self.model = whisper.load_model("medium")

    def transcribe(self, audio_path):
        result = self.model.transcribe(audio_path, language="ar")
        return result["text"]

def chunk_text(text, chunk_size=200):
    words = text.split()
    chunks = []
    for i in range(0, len(words), chunk_size):
        chunk = " ".join(words[i:i+chunk_size])
        chunks.append(chunk)
    return chunks

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

class ArabicSummarizer:
    def __init__(self):
        self.tokenizer = AutoTokenizer.from_pretrained("UBC-NLP/AraT5-base")
        self.model = AutoModelForSeq2SeqLM.from_pretrained("UBC-NLP/AraT5-base")

    def summarize(self, text):
        inputs = self.tokenizer(text, return_tensors="pt", truncation=True)
        summary_ids = self.model.generate(
            **inputs,
            max_length=120,
            min_length=40,
            num_beams=4
        )
        return self.tokenizer.decode(summary_ids[0], skip_special_tokens=True)

from sentence_transformers import SentenceTransformer
import numpy as np

class ArabicEmbedder:
    def __init__(self):
        self.model = SentenceTransformer(
            "paraphrase-multilingual-mpnet-base-v2"
        )

    def encode(self, texts):
        return np.array(self.model.encode(texts)).astype("float32")

import faiss

class SemanticSearch:
    def __init__(self, dim):
        self.index = faiss.IndexFlatL2(dim)
        self.texts = []

    def add(self, embeddings, texts):
        self.index.add(embeddings)
        self.texts.extend(texts)

    def search(self, query_embedding, k=3):
        D, I = self.index.search(query_embedding, k)
        return [self.texts[i] for i in I[0]]

from fastapi import FastAPI, UploadFile
import shutil

# Removed: from app.asr import ArabicASR
# Removed: from app.summarizer import ArabicSummarizer
# Removed: from app.embeddings import ArabicEmbedder
# Removed: from app.search import SemanticSearch
# Removed: from app.utils import chunk_text

app = FastAPI()

asr = ArabicASR()
summarizer = ArabicSummarizer()
embedder = ArabicEmbedder()
search_engine = SemanticSearch(dim=768)

@app.post("/upload")
async def upload_audio(file: UploadFile):
    path = f"data/audio/{file.filename}"
    with open(path, "wb") as buffer:
        shutil.copyfileobj(file.file, buffer)

    transcript = asr.transcribe(path)
    chunks = chunk_text(transcript)

    embeddings = embedder.encode(chunks)
    search_engine.add(embeddings, chunks)

    summary = summarizer.summarize(transcript)

    return {
        "transcript": transcript,
        "summary": summary
    }

@app.get("/search")
def search(query: str):
    q_emb = embedder.encode([query])
    results = search_engine.search(q_emb)
    return {"results": results}

from jiwer import wer

reference = "النص الصحيح"
hypothesis = "النص الناتج"

print("WER:", wer(reference, hypothesis))

from rouge_score import rouge_scorer

scorer = rouge_scorer.RougeScorer(['rouge1', 'rougeL'], use_stemmer=True)
summary = hypothesis  # Assigning hypothesis as a placeholder for summary
scores = scorer.score(reference, summary)
print(scores)

print("REFERENCE:\n", reference)
print("SUMMARY:\n", summary)

set(reference.split()) & set(summary.split())

import re

def normalize_arabic(text):
    text = re.sub("[ًٌٍَُِّْـ]", "", text)
    text = re.sub("أ|إ|آ", "ا", text)
    text = re.sub("ة", "ه", text)
    text = re.sub("ى", "ي", text)
    return text

reference = normalize_arabic(reference)
summary = normalize_arabic(summary)

from rouge_score import rouge_scorer

scorer = rouge_scorer.RougeScorer(
    ['rouge1', 'rougeL'],
    use_stemmer=False
)

scores = scorer.score(reference, summary)
print(scores)

"""### Using actual transcript files for evaluation

Let's load the content of the provided transcript files and use them as `reference` and `hypothesis` for more meaningful evaluation.
"""

import re

def normalize_arabic(text):
    text = re.sub("[ًٌٍَُِّْـ]", "", text)
    text = re.sub("أ|إ|آ", "ا", text)
    text = re.sub("ة", "ه", text)
    text = re.sub("ى", "ي", text)
    return text

with open('/content/orthographic-transcript.txt', 'r', encoding='utf-8') as f:
    file_reference = f.read().strip()

with open('/content/phonetic-transcipt.txt', 'r', encoding='utf-8') as f:
    file_hypothesis = f.read().strip()

# Normalize the text using the previously defined function
file_reference_normalized = normalize_arabic(file_reference)
file_hypothesis_normalized = normalize_arabic(file_hypothesis)

print("Normalized Reference from file:", file_reference_normalized)
print("Normalized Hypothesis from file:", file_hypothesis_normalized)

"""### Re-calculate WER with file data"""

from jiwer import wer

wer_score_file = wer(file_reference_normalized, file_hypothesis_normalized)
print(f"WER with file data: {wer_score_file}")

"""### Re-calculate ROUGE scores with file data"""

from rouge_score import rouge_scorer

scorer_file = rouge_scorer.RougeScorer(
    ['rouge1', 'rougeL'],
    use_stemmer=False
)

scores_file = scorer_file.score(file_reference_normalized, file_hypothesis_normalized)
print(f"ROUGE scores with file data: {scores_file}")

import re

def normalize_arabic(text):
    text = re.sub("[ًٌٍَُِّْـ]", "", text)
    text = re.sub("أ|إ|آ", "ا", text)
    text = re.sub("ة", "ه", text)
    text = re.sub("ى", "ي", text)
    return text

with open('/content/orthographic-transcript.txt', 'r', encoding='utf-8') as f:
    file_reference = f.read().strip()

with open('/content/phonetic-transcipt.txt', 'r', encoding='utf-8') as f:
    file_hypothesis = f.read().strip()

# Normalize the text using the previously defined function
file_reference_normalized = normalize_arabic(file_reference)
file_hypothesis_normalized = normalize_arabic(file_hypothesis)

print("Normalized Reference from file:", file_reference_normalized)
print("Normalized Hypothesis from file:", file_hypothesis_normalized)

"""### Re-calculate WER with file data"""

import re
from jiwer import wer

def normalize_arabic(text):
    text = re.sub("[ًٌٍَُِّْـ]", "", text)
    text = re.sub("أ|إ|آ", "ا", text)
    text = re.sub("ة", "ه", text)
    text = re.sub("ى", "ي", text)
    return text

with open('/content/orthographic-transcript.txt', 'r', encoding='utf-8') as f:
    file_reference = f.read().strip()

with open('/content/phonetic-transcipt.txt', 'r', encoding='utf-8') as f:
    file_hypothesis = f.read().strip()

# Normalize the text using the previously defined function
file_reference_normalized = normalize_arabic(file_reference)
file_hypothesis_normalized = normalize_arabic(file_hypothesis)

wer_score_file = wer(file_reference_normalized, file_hypothesis_normalized)
print(f"WER with file data: {wer_score_file}")

"""### Re-calculate ROUGE scores with file data"""

import re

def normalize_arabic(text):
    text = re.sub("[ًٌٍَُِّْـ]", "", text)
    text = re.sub("أ|إ|آ", "ا", text)
    text = re.sub("ة", "ه", text)
    text = re.sub("ى", "ي", text)
    return text

with open('/content/orthographic-transcript.txt', 'r', encoding='utf-8') as f:
    file_reference = f.read().strip()

with open('/content/phonetic-transcipt.txt', 'r', encoding='utf-8') as f:
    file_hypothesis = f.read().strip()

# Normalize the text using the previously defined function
file_reference_normalized = normalize_arabic(file_reference)
file_hypothesis_normalized = normalize_arabic(file_hypothesis)

print("Normalized Reference from file:", file_reference_normalized)
print("Normalized Hypothesis from file:", file_hypothesis_normalized)

from rouge_score import rouge_scorer

scorer_file = rouge_scorer.RougeScorer(
    ['rouge1', 'rougeL'],
    use_stemmer=False
)

scores_file = scorer_file.score(file_reference_normalized, file_hypothesis_normalized)
print(f"ROUGE scores with file data: {scores_file}")

from rouge_score import rouge_scorer

scorer_file = rouge_scorer.RougeScorer(
    ['rouge1', 'rougeL'],
    use_stemmer=False
)

scores_file = scorer_file.score(file_reference_normalized, file_hypothesis_normalized)
print(f"ROUGE scores with file data: {scores_file}")

import re

def normalize_arabic(text):
    text = re.sub("[ًٌٍَُِّْـ]", "", text)
    text = re.sub("أ|إ|آ", "ا", text)
    text = re.sub("ة", "ه", text)
    text = re.sub("ى", "ي", text)
    return text

with open('/content/orthographic-transcript.txt', 'r', encoding='utf-8') as f:
    file_reference = f.read().strip()

with open('/content/phonetic-transcipt.txt', 'r', encoding='utf-8') as f:
    file_hypothesis = f.read().strip()

# Normalize the text using the previously defined function
file_reference_normalized = normalize_arabic(file_reference)
file_hypothesis_normalized = normalize_arabic(file_hypothesis)

print("Normalized Reference from file:", file_reference_normalized)
print("Normalized Hypothesis from file:", file_hypothesis_normalized)

from rouge_score import rouge_scorer

scorer_file = rouge_scorer.RougeScorer(
    ['rouge1', 'rougeL'],
    use_stemmer=False
)

scores_file = scorer_file.score(file_reference_normalized, file_hypothesis_normalized)
print(f"ROUGE scores with file data: {scores_file}")

"""### Re-calculate WER with file data"""

from jiwer import wer

wer_score_file = wer(file_reference_normalized, file_hypothesis_normalized)
print(f"WER with file data: {wer_score_file}")

"""### Re-calculate ROUGE scores with file data"""

import re
from rouge_score import rouge_scorer

def normalize_arabic(text):
    text = re.sub("[ًٌٍَُِّْـ]", "", text)
    text = re.sub("أ|إ|آ", "ا", text)
    text = re.sub("ة", "ه", text)
    text = re.sub("ى", "ي", text)
    return text

with open('/content/orthographic-transcript.txt', 'r', encoding='utf-8') as f:
    file_reference = f.read().strip()

with open('/content/phonetic-transcipt.txt', 'r', encoding='utf-8') as f:
    file_hypothesis = f.read().strip()

# Normalize the text using the previously defined function
file_reference_normalized = normalize_arabic(file_reference)
file_hypothesis_normalized = normalize_arabic(file_hypothesis)

scorer_file = rouge_scorer.RougeScorer(
    ['rouge1', 'rougeL'],
    use_stemmer=False
)

scores_file = scorer_file.score(file_reference_normalized, file_hypothesis_normalized)
print(f"ROUGE scores with file data: {scores_file}")